# Generated by Django 5.2.7 on 2025-10-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='Nom')),
                ('lastName', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('company', models.CharField(max_length=100, verbose_name='Entréprise / Organisation')),
                ('service', models.CharField(max_length=200, verbose_name='Services souhaité')),
                ('message', models.TextField(verbose_name='Message')),
                ('budget', models.CharField(blank=True, max_length=120, null=True, verbose_name='Budget Prévisionnel')),
                ('newsletter', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
            },
        ),
    ]
